Updated JS wrapper workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -243,13 +243,28 @@ jobs:
         if: inputs.dev == true && inputs.jsTag != ''
         run: |
           echo "Getting js wrapper ${{inputs.jsTag}} version..."
-          JS_VERSION_NAME=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/Checkmarx/packages/npm/ast-cli-javascript-wrapper/versions | jq '.[]|select((.name | contains("-${{inputs.jsTag}}.0")) or .name == "${{inputs.jsTag}}")|.name' | tr -d '"')
-          if [ ${JS_VERSION_NAME} != '' ]; then
-          echo "Install JS Wrapper version  ${JS_VERSION_NAME}"
-          cd packages/core
-          npm install "@checkmarx/ast-cli-javascript-wrapper@"${JS_VERSION_NAME}
+
+          # Remove 'v' prefix if present
+          TAG_WITHOUT_V="${{inputs.jsTag}}"
+          TAG_WITHOUT_V="${TAG_WITHOUT_V#v}"
+
+          JS_VERSION_NAME=$(curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/orgs/Checkmarx/packages/npm/ast-cli-javascript-wrapper/versions \
+          | jq -r --arg tag "$TAG_WITHOUT_V" '.[] | select(.name == $tag or .name | contains("-" + $tag)) | .name' \
+          | head -n 1)
+
+          echo "JS Wrapper version found: '$JS_VERSION_NAME'"
+
+          if [ -n "${JS_VERSION_NAME}" ]; then
+            echo "Installing JS Wrapper version ${JS_VERSION_NAME}"
+            cd packages/core
+            npm install "@checkmarx/ast-cli-javascript-wrapper@${JS_VERSION_NAME}"
           else
-            echo "JS wrapper with version ${JS_VERSION_NAME} not found"
+            echo "JS wrapper matching tag ${{inputs.jsTag}} not found"
+          exit 1
           fi
 
       # EXTRACT CLI VERSION
