Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: VSCode Release
+name: Checkmarx Extension Release
 
 on:
   workflow_call:
@@ -58,188 +58,203 @@ jobs:
   release:
     runs-on: ubuntu-latest
     env:
-      BRANCH_NAME: update-npm-version
+      BRANCH_NAME: update-checkmarx-version
       GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
     outputs:
       TAG_NAME: ${{ steps.generate_tag_name.outputs.TAG_NAME }}
       CLI_VERSION: ${{ steps.extract_cli_version.outputs.CLI_VERSION }}
     steps:
-    # CHECKOUT PROJECT
-    - name: Checkout
-      uses: actions/checkout@v4.1.0
+      # CHECKOUT PROJECT
+      - name: Checkout
+        uses: actions/checkout@v4.1.0
 
-    # GIT CONFIGURATION
-    - run: |
-        git config user.name vscode-releases
-        git config user.email vscode-releases@github.com
+      # GIT CONFIGURATION
+      - run: |
+          git config user.name vscode-releases
+          git config user.email vscode-releases@github.com
 
-    # AUTHENTICATE TO GITHUB PACKAGE REGISTRY
-    - name: Authenticate with GitHub package registry
-      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
+      # AUTHENTICATE TO GITHUB PACKAGE REGISTRY
+      - name: Authenticate with GitHub package registry
+        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
 
-    # SETUP NODE
-    - name: Setup Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: 22.11.0
+      # SETUP NODE
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 22.11.0
 
-    # GET TAG NAME
-    - name: Generate Tag name
-      id: generate_tag_name
-      run: |
-        echo "vscodeTag input: ${{ inputs.vscodeTag }}"
-        if [ ${{ inputs.dev }} == true ]; then
-          echo "Running npm version prerelease with preid=${{ inputs.vscodeTag }}"
-          TAG_NAME=$(npm version prerelease --preid=${{ inputs.vscodeTag }} --no-git-tag-version --allow-same-version 2>/dev/null || echo "error")
-          if [ "$TAG_NAME" == "error" ]; then
-            echo "npm version prerelease command failed"
-            exit 1
+      # GET TAG NAME
+      - name: Generate Tag name
+        id: generate_tag_name
+        run: |
+          echo "vscodeTag input: ${{ inputs.vscodeTag }}"
+          cd packages/checkmarx
+          if [ ${{ inputs.dev }} == true ]; then
+            echo "Running npm version prerelease with preid=${{ inputs.vscodeTag }}"
+            TAG_NAME=$(npm version prerelease --preid=${{ inputs.vscodeTag }} --no-git-tag-version --allow-same-version 2>/dev/null || echo "error")
+            if [ "$TAG_NAME" == "error" ]; then
+              echo "npm version prerelease command failed"
+              exit 1
+            fi
+          else
+            echo "Running npm version minor"
+            TAG_NAME=$(npm version minor --no-git-tag-version 2>/dev/null || echo "error")
+            if [ "$TAG_NAME" == "error" ]; then
+              echo "npm version minor command failed"
+              exit 1
+            fi
           fi
-        else
-          echo "Running npm version minor"
-          TAG_NAME=$(npm version minor --no-git-tag-version 2>/dev/null || echo "error")
-          if [ "$TAG_NAME" == "error" ]; then
-            echo "npm version minor command failed"
-            exit 1
+          # Add checkmarx-v prefix to tag
+          TAG_NAME="checkmarx-${TAG_NAME}"
+          echo "Generated TAG_NAME: $TAG_NAME"
+          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
+          echo "::set-output name=TAG_NAME::$TAG_NAME"
+
+      # INSTALL NPM DEPENDENCIES
+      - name: Install dependencies
+        run: |
+          cd packages/core && npm install
+          cd ../checkmarx && npm install
+
+      # GET AND INSTALL JS WRAPPER VERSION PROVIDED BY USER
+      - name: Get and install JS Wrapper if provided by user
+        if: inputs.dev == true && inputs.jsTag != ''
+        run: |
+          echo "Getting js wrapper ${{inputs.jsTag}} version..."
+
+          JS_VERSION_NAME=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/Checkmarx/packages/npm/ast-cli-javascript-wrapper/versions | jq '.[]|select((.name | contains("-${{inputs.jsTag}}.0")) or .name == "${{inputs.jsTag}}")|.name' | tr -d '"')
+
+          if [ ${JS_VERSION_NAME} != '' ]; then
+            echo "Install JS Wrapper version  ${JS_VERSION_NAME}"
+            cd packages/core
+            npm install "@checkmarx/ast-cli-javascript-wrapper@"${JS_VERSION_NAME}
+          else
+            echo "JS wrapper with version ${JS_VERSION_NAME} not found"
           fi
-        fi
-        echo "Generated TAG_NAME: $TAG_NAME"
-        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
-        echo "::set-output name=TAG_NAME::$TAG_NAME"
 
-    # INSTALL NPM DEPENDENCIES
-    - name: Install dependencies
-      run: npm install
+      - name: Extract CLI version
+        id: extract_cli_version
+        run: |
+          CLI_VERSION=$(./packages/core/node_modules/@checkmarx/ast-cli-javascript-wrapper/dist/main/wrapper/resources/cx-linux version | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+')
+          echo "CLI version being packed is $CLI_VERSION"
+          echo "CLI_VERSION=$CLI_VERSION" >> $GITHUB_ENV
+          echo "::set-output name=CLI_VERSION::$CLI_VERSION"
 
-    # GET AND INSTALL JS WRAPPER VERSION PROVIDED BY USER
-    - name: Get and install JS Wrapper if provided by user
-      if: inputs.dev == true && inputs.jsTag != ''
-      run: |
-        echo "Getting js wrapper ${{inputs.jsTag}} version..."
+      # INSTALL VSCE
+      - name: Install VSCE
+        run: npm install -g vsce
 
-        JS_VERSION_NAME=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/Checkmarx/packages/npm/ast-cli-javascript-wrapper/versions | jq '.[]|select((.name | contains("-${{inputs.jsTag}}.0")) or .name == "${{inputs.jsTag}}")|.name' | tr -d '"')
+      # BUILD AND PACKAGE PROJECT
+      - name: Build core package
+        run: cd packages/core && npm run compile
 
-        if [ ${JS_VERSION_NAME} != '' ]; then
-          echo "Install JS Wrapper version  ${JS_VERSION_NAME}"
-          npm install "@checkmarx/ast-cli-javascript-wrapper@"${JS_VERSION_NAME}
-        else
-          echo "JS wrapper with version ${JS_VERSION_NAME} not found"
-        fi
+      - name: Build Checkmarx extension
+        run: cd packages/checkmarx && npm run compile
 
-    - name: Extract CLI version
-      id: extract_cli_version
-      run: |
-        CLI_VERSION=$(./node_modules/@checkmarx/ast-cli-javascript-wrapper/dist/main/wrapper/resources/cx-linux version | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+')
-        echo "CLI version being packed is $CLI_VERSION"
-        echo "CLI_VERSION=$CLI_VERSION" >> $GITHUB_ENV
-        echo "::set-output name=CLI_VERSION::$CLI_VERSION"
+      # PACKAGE PROJECT
+      - name: Package .vsix file
+        run: |
+          cd packages/checkmarx
+          if [ ${{ inputs.dev }} == true ]; then
+            node ../../.github/scripts/updateDevVersionCheckmarx.js
+            vsce package --pre-release --allow-star-activation --no-dependencies
+          else
+            vsce package --allow-star-activation --no-dependencies
+          fi
 
-    # INSTALL VSCE
-    - name: Install VSCE
-      run: npm install -g vsce
+      # CREATE GH RELEASE NAME
+      - name: Handle GH Release name
+        run: |
+          VSIX_TAG_NAME=$(cat packages/checkmarx/package.json | jq .version | cut -d'"' -f 2)
+          echo "VSIX_TAG_NAME=$VSIX_TAG_NAME" >> $GITHUB_ENV
 
-    # PACKAGE PROJECT
-    - name: Package .vsix file
-      run: |
-        if [ ${{ inputs.dev }} == true ]; then
-          node .github/scripts/updateDevVersion.js
-          vsce package --pre-release
-        else
-          vsce package
-        fi
+          if [ ${{ inputs.dev }} == true ]; then
+            echo "GH_RELEASE_NAME=${{env.TAG_NAME}} (${VSIX_TAG_NAME})" >> $GITHUB_ENV
+          else
+            echo "GH_RELEASE_NAME=${{env.TAG_NAME}}" >> $GITHUB_ENV
+          fi
 
-    # CREATE GH RELEASE NAME
-    - name: Handle GH Release name
-      run: |
-        VSIX_TAG_NAME=$(cat package.json | jq .version | cut -d'"' -f 2)
-        echo "VSIX_TAG_NAME=$VSIX_TAG_NAME" >> $GITHUB_ENV
+      # CREATE PR FOR VERSION
+      - name: Create Pull Request
+        id: create_pr
+        if: inputs.dev == false
+        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e #v6.0.5
+        with:
+          token: ${{ env.GITHUB_TOKEN }}
+          branch: ${{ env.BRANCH_NAME }}
+          title: "Update Checkmarx Extension Version - Automated Changes"
+          body: "This is an automated PR created by GitHub Actions to update the Checkmarx extension version"
+          base: main
+          draft: false
 
-        if [ ${{ inputs.dev }} == true ]; then
-          echo "GH_RELEASE_NAME=${{env.TAG_NAME}} (${VSIX_TAG_NAME})" >> $GITHUB_ENV
-        else
-          echo "GH_RELEASE_NAME=${{env.TAG_NAME}}" >> $GITHUB_ENV
-        fi
+      # WAIT FOR PR CREATION
+      - name: Wait for PR to be created
+        id: pr
+        if: inputs.dev == false
+        uses: octokit/request-action@872c5c97b3c85c23516a572f02b31401ef82415d #v2.3.1
+        with:
+          route: GET /repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ env.BRANCH_NAME }}
 
-    # CREATE PR FOR VERSION
-    - name: Create Pull Request
-      id: create_pr
-      if: inputs.dev == false
-      uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e #v6.0.5
-      with:
-        token: ${{ env.GITHUB_TOKEN }}
-        branch: ${{ env.BRANCH_NAME }}
-        title: "Update Version - Automated Changes"
-        body: "This is an automated PR created by GitHub Actions"
-        base: main
-        draft: false
+      # MERGE PR TO MAIN
+      - name: Merge Pull Request
+        if: inputs.dev == false
+        uses: octokit/request-action@872c5c97b3c85c23516a572f02b31401ef82415d #v2.3.1
+        with:
+          route: PUT /repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request-number }}/merge
+          merge_method: squash
 
-    # WAIT FOR PR CREATION
-    - name: Wait for PR to be created
-      id: pr
-      if: inputs.dev == false
-      uses: octokit/request-action@872c5c97b3c85c23516a572f02b31401ef82415d #v2.3.1
-      with:
-        route: GET /repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ env.BRANCH_NAME }}
+      # PUSH TAGS IF IT IS A RELEASE
+      - name: Push tag
+        if: inputs.dev == false
+        run: |
+          git pull
+          git tag ${{ env.TAG_NAME }}
+          git push --tags
 
-    # MERGE PR TO MAIN
-    - name: Merge Pull Request
-      if: inputs.dev == false
-      uses: octokit/request-action@872c5c97b3c85c23516a572f02b31401ef82415d #v2.3.1
-      with:
-        route: PUT /repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request-number }}/merge
-        merge_method: squash
+      # CREATE GH RELEASE
+      - name: Create Release
+        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v1
+        with:
+          name: ${{env.GH_RELEASE_NAME}}
+          tag_name: ${{env.TAG_NAME}}
+          generate_release_notes: true
+          files: packages/checkmarx/ast-results-${{env.VSIX_TAG_NAME}}.vsix
+          prerelease: ${{ inputs.dev }}
 
-    # PUSH TAGS IF IT IS A RELEASE
-    - name: Push tag
-      if: inputs.dev == false
-      run: |
-        git pull
-        git tag ${{ env.TAG_NAME }}
-        git push --tags
+      # GENERATE AND WRITE CHANGELOG TO FILE
+      - name: Generate release changelog
+        uses: BobAnkh/auto-generate-changelog@b8e208489ce4f71adc3b6467020dd276f1445e8a #v1.2.5
+        with:
+          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          PATH: "packages/checkmarx/CHANGELOG.md"
 
-    # CREATE GH RELEASE
-    - name: Create Release
-      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v1
-      with:
-        name: ${{env.GH_RELEASE_NAME}}
-        tag_name: ${{env.TAG_NAME}}
-        generate_release_notes: true
-        files: ast-results-${{env.VSIX_TAG_NAME}}.vsix
-        prerelease: ${{ inputs.dev }}
+      # PUBLISH TO MARKETPLACE
+      - name: Publish to VSCode Marketplace
+        env:
+          MARKET_TOKEN: ${{ secrets.MARKET_TOKEN }}
+        if: env.MARKET_TOKEN != null && (inputs.dev == false || (inputs.dev == true && inputs.publish == true))
+        run: |
+          cd packages/checkmarx
+          if [ ${{ inputs.dev }} == true ]; then
+            vsce publish --pre-release -p ${{ env.MARKET_TOKEN }}
+          else
+            vsce publish -p ${{ env.MARKET_TOKEN }}
+          fi
 
-    # GENERATE AND WRITE CHANGELOG TO FILE
-    - name: Generate release changelog
-      uses: BobAnkh/auto-generate-changelog@b8e208489ce4f71adc3b6467020dd276f1445e8a #v1.2.5
-      with:
-        ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-        PATH: "CHANGELOG.md"
-
-    # PUBLISH TO MARKETPLACE
-    - name: Publish to VSCode Marketplace
-      env:
-        MARKET_TOKEN: ${{ secrets.MARKET_TOKEN }}
-      if: env.MARKET_TOKEN != null && (inputs.dev == false || (inputs.dev == true && inputs.publish == true))
-      run: |
-        if [ ${{ inputs.dev }} == true ]; then
-          vsce publish --pre-release -p ${{ env.MARKET_TOKEN }}
-        else
-          vsce publish -p ${{ env.MARKET_TOKEN }}
-        fi
-        
-    - name: Publish to Open VSX (ovsx)
-      if: env.OPEN_VSX_TOKEN != null && (inputs.dev == false || (inputs.dev == true && inputs.publish == true))
-      env:
-        OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
-      run: |
-        npm install -g ovsx
-        ovsx publish ast-results-${{env.VSIX_TAG_NAME}}.vsix --pat ${{ env.OPEN_VSX_TOKEN }}
+      - name: Publish to Open VSX (ovsx)
+        if: env.OPEN_VSX_TOKEN != null && (inputs.dev == false || (inputs.dev == true && inputs.publish == true))
+        env:
+          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
+        run: |
+          npm install -g ovsx
+          ovsx publish packages/checkmarx/ast-results-${{env.VSIX_TAG_NAME}}.vsix --pat ${{ env.OPEN_VSX_TOKEN }}
 
   notify:
     if: inputs.dev == false
     needs: release
     uses: Checkmarx/plugins-release-workflow/.github/workflows/release-notify.yml@main
     with:
-      product_name: VS Code
+      product_name: VS Code - Checkmarx
       release_version: ${{ needs.release.outputs.TAG_NAME }}
       cli_release_version: ${{ needs.release.outputs.CLI_VERSION }}
       release_author: "Phoenix Team"
